title: Fat Rat's Dev Corner
description: Welcome to my site that I will post any personal projects or updates on my
google_analytics: 
show_downloads: true
theme: jekyll-theme-slate

gems:
  - jekyll-mentions
